### ISSUE TITLE
Step file for PCB

### ISSUE THREAD

**Issue by Nirzhuk** [kreme123/Kolibrimini#1]
Hello,

If you can release the step file for the PCB because I want to develop an acrylic case for this keyboard. 
Thanks!

**Comment by kreme123** [comment]
Step file for PCB added

**Comment by Nirzhuk** [comment]
Thanks!

**Comment by Nirzhuk** [comment]
@kreme123 I might need the plate too because I'm doing some type of gasket with acrylic :P
